// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: MIT

//! `Keel.LinkParser`: `text`, `shortenUrl` and the read-only `linkedText`
//! (`crate::linkify`). `Sailfish.Silica.private`'s `LinkParser`
//! (`qml/private/LinkParser.qml`) is this type; Silica's BSD
//! `LinkedLabel.qml` uses it.

#![allow(
    clippy::unnecessary_box_returns,
    reason = "the constructor is generated by cxx_qt::bridge"
)]

#[cxx_qt::bridge]
pub mod qobject {
    unsafe extern "C++" {
        include!("cxx-qt-lib/qstring.h");
        type QString = cxx_qt_lib::QString;
    }

    extern "RustQt" {
        #[qobject]
        #[namespace = "keel"]
        #[qproperty(QString, text, READ, WRITE, NOTIFY = inputs_changed)]
        #[qproperty(bool, shorten_url, cxx_name = "shortenUrl", READ, WRITE, NOTIFY = inputs_changed)]
        #[qproperty(QString, linked_text, cxx_name = "linkedText", READ = linked_text_value, NOTIFY = inputs_changed)]
        type LinkParser = super::LinkParserRust;

        #[qsignal]
        #[cxx_name = "inputsChanged"]
        fn inputs_changed(self: Pin<&mut Self>);

        #[cxx_name = "linkedTextValue"]
        fn linked_text_value(self: &Self) -> QString;
    }
}

use cxx_qt_lib::QString;

#[derive(Default)]
pub struct LinkParserRust {
    text: QString,
    shorten_url: bool,
}

impl qobject::LinkParser {
    pub fn linked_text_value(&self) -> QString {
        QString::from(
            crate::linkify::linkify(&self.text().to_string(), *self.shorten_url()).as_str(),
        )
    }
}
