#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Patrick Quinn
# SPDX-License-Identifier: Apache-2.0
#
# New file, added by Shipwright in 2026 (not part of upstream xmatic).
"""Regenerates core/data/mcc-dialling.tsv, the table that turns the SIM's
mobile country code (or the locale's country) into a dialling plan for
contact matching (core/src/dialling.rs).

Two sources, both Apache-2.0, pinned so a regeneration is reproducible:

* MCC to ISO 3166 region: AOSP `MccTable.java` (built from the ITU list of
  mobile country codes, ITU-T E.212 complement, and ISO 3166).
* Region to calling code and national/international prefixes: libphonenumber
  `PhoneNumberMetadata.xml` (ITU-T E.164 assignments).

Usage: tools/mcc-dialling.py MccTable.java PhoneNumberMetadata.xml > core/data/mcc-dialling.tsv
Fetch the inputs from the two URLs below (the AOSP one with ?format=TEXT is
base64).
"""

import re
import sys
import xml.etree.ElementTree as ET

AOSP_URL = (
    "https://android.googlesource.com/platform/frameworks/opt/telephony/+/"
    "307806916047d68377ff74674f95ca499243e068/src/java/com/android/internal/"
    "telephony/MccTable.java"
)
LIBPHONENUMBER_URL = (
    "https://github.com/google/libphonenumber/blob/v9.0.40/resources/"
    "PhoneNumberMetadata.xml"
)
DIGITS = re.compile(r"^[0-9]+$")


def international_prefix(attributes):
    """A dialled prefix as plain digits, or "-" where the metadata only has a
    pattern with no plain first alternative."""
    preferred = attributes.get("preferredInternationalPrefix", "")
    if DIGITS.match(preferred):
        return preferred
    pattern = attributes.get("internationalPrefix", "")
    first = pattern.split("|")[0]
    return first if DIGITS.match(first) else "-"


def main(mcc_java, metadata_xml):
    entries = re.findall(
        r'new MccEntry\((\d+),\s*"(\w*)",\s*\d+\)',
        open(mcc_java, encoding="utf-8").read(),
    )
    regions = {
        territory.get("id"): territory.attrib
        for territory in ET.parse(metadata_xml).getroot().iter("territory")
    }
    # REUSE-IgnoreStart
    print("# SPDX-FileCopyrightText: 2006 The Android Open Source Project")
    print("# SPDX-FileCopyrightText: 2009 The Libphonenumber Authors")
    print("# SPDX-FileCopyrightText: 2026 Patrick Quinn")
    print("# SPDX-License-Identifier: Apache-2.0")
    # REUSE-IgnoreEnd
    print("#")
    print("# Generated by tools/mcc-dialling.py; do not edit by hand.")
    print("# Mobile country code (ITU-T E.212) to region and dialling plan.")
    print("# MCC and region from AOSP MccTable.java:")
    print(f"#   {AOSP_URL}")
    print("# Calling code (ITU-T E.164), national (trunk) prefix and international")
    print("# prefix from libphonenumber:")
    print(f"#   {LIBPHONENUMBER_URL}")
    print("# '-' means none (national prefix) or not a plain digit string")
    print("# (international prefix).")
    print("#")
    print("# mcc\tregion\tcalling_code\tnational_prefix\tinternational_prefix")
    missing = []
    for mcc, iso in sorted(entries, key=lambda entry: int(entry[0])):
        region = iso.upper()
        attributes = regions.get(region)
        if attributes is None:
            missing.append(f"{mcc} {region}")
            continue
        national = attributes.get("nationalPrefix") or "-"
        print(
            f"{mcc}\t{region}\t{attributes['countryCode']}\t{national}\t"
            f"{international_prefix(attributes)}"
        )
    if missing:
        print("not in libphonenumber: " + ", ".join(missing), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
