// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: GPL-3.0-or-later

//! The Reef catalogue: one JSON file per repository directory
//! (`sailfishos/<release>/<arch>/catalogue.json`), generated by
//! `tools/build/reef/gen-catalogue.py` at publish time.
//!
//! docs/plan.md ("Versioning and release"): each entry records the Sailfish
//! releases it was tested on, and the client hides packages not tested on
//! the phone's release. RPM metadata cannot carry that, so the catalogue is
//! a separate file.
//!
//! Authenticity: packages are RPM-signed and zypp checks them, so a forged
//! catalogue cannot get an unsigned package installed. It could unhide an
//! untested package or lie about permissions; signing the catalogue is a
//! follow-up (see the README).

use serde::{Deserialize, Serialize};

use crate::release::SailfishRelease;

/// The schema version this client understands.
pub const SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalogue {
    pub schema: u32,
    /// The release path component this catalogue was published under
    /// (`5.2.0.17`, or `5.2` for a major.minor repository).
    pub release: String,
    pub arch: String,
    /// RFC 3339, informational.
    #[serde(default)]
    pub generated_at: String,
    pub packages: Vec<Package>,
    /// RPM names the store shows first, in this order (its Featured row).
    /// `parse` drops names not in `packages` and repeats.
    #[serde(default)]
    pub featured: Vec<String>,
}

/// Screenshots kept per package; the rest are dropped.
pub const MAX_SCREENSHOTS: usize = 8;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Package {
    /// RPM name.
    pub name: String,
    /// RPM `version-release` of the published build.
    pub version: String,
    pub title: String,
    pub summary: String,
    #[serde(default)]
    pub description: String,
    #[serde(default = "default_category")]
    pub category: String,
    /// Full release strings (`5.2.0.17`) this exact build was tested on.
    pub tested_on: Vec<String>,
    /// Sailjail permissions the app requests, by name (for example
    /// `Bluetooth`, `Audio`), shown before install.
    #[serde(default)]
    pub permissions: Vec<String>,
    /// False for apps that run outside Sailjail (the store client itself,
    /// daemons). Shown prominently before install.
    #[serde(default = "default_true")]
    pub sandboxed: bool,
    pub licence: LicenceModel,
    /// SPDX expression of the package's own licence.
    #[serde(default)]
    pub spdx: Option<String>,
    #[serde(default)]
    pub size: Option<u64>,
    #[serde(default)]
    pub homepage: Option<String>,
    #[serde(default)]
    pub source: Option<String>,
    /// The launcher icon: a path relative to the repository directory
    /// (`assets/<name>.png`). The client fetches it from there and nowhere
    /// else, so a catalogue cannot make the store load an arbitrary image.
    /// Dropped by `parse` unless [`is_asset_path`] accepts it.
    #[serde(default)]
    pub icon: Option<String>,
    /// Screenshots, relative paths like `icon`, at most [`MAX_SCREENSHOTS`].
    #[serde(default)]
    pub screenshots: Vec<String>,
    /// Who publishes the app, shown under its title.
    #[serde(default)]
    pub publisher: String,
    /// The day the app was first published, `YYYY-MM-DD`; the store marks
    /// recent ones as new. Dropped by `parse` when malformed.
    #[serde(default)]
    pub added: Option<String>,
    /// The Keel compatibility tier the developer portal's review measured
    /// with `keel-compat` (docs/plan.md, "Compatibility target"): `A`, `B`,
    /// `none` (neither reached), or `not-applicable` (no Silica imports).
    /// Informational; unknown values are kept as they are so a newer portal
    /// does not break older clients. Absent in first-party entries and in
    /// catalogues generated before the field existed.
    #[serde(default)]
    pub keel_tier: Option<String>,
}

/// How a package is paid for (docs/plan.md, "Pricing model").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "model", rename_all = "snake_case", deny_unknown_fields)]
pub enum LicenceModel {
    Free,
    OneOff {
        app_id: String,
        purchase_url: String,
    },
    Subscription {
        app_id: String,
        purchase_url: String,
    },
}

impl LicenceModel {
    /// The licence app id, for paid packages.
    pub fn app_id(&self) -> Option<&str> {
        match self {
            LicenceModel::Free => None,
            LicenceModel::OneOff { app_id, .. } | LicenceModel::Subscription { app_id, .. } => {
                Some(app_id)
            }
        }
    }
}

fn default_category() -> String {
    "Other".into()
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CatalogueError {
    Json(String),
    UnsupportedSchema(u32),
    WrongArch {
        expected: String,
        found: String,
    },
    DuplicatePackage(String),
    /// A package entry the client must not act on (bad licence app id,
    /// non-https purchase link).
    InvalidPackage {
        name: String,
        why: String,
    },
}

impl std::fmt::Display for CatalogueError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CatalogueError::Json(e) => write!(f, "catalogue is not valid JSON: {e}"),
            CatalogueError::UnsupportedSchema(v) => {
                write!(
                    f,
                    "catalogue schema {v} is newer than this client; update Reef"
                )
            }
            CatalogueError::WrongArch { expected, found } => {
                write!(f, "catalogue is for {found}, this phone is {expected}")
            }
            CatalogueError::DuplicatePackage(n) => write!(f, "catalogue lists {n} twice"),
            CatalogueError::InvalidPackage { name, why } => {
                write!(f, "catalogue entry {name} is invalid: {why}")
            }
        }
    }
}

impl std::error::Error for CatalogueError {}

impl Catalogue {
    /// Parses and sanity-checks a downloaded catalogue.
    ///
    /// The catalogue is not signed (see the module docs), so everything the
    /// client acts on is checked here: licence app ids must be well-formed
    /// (they become file names in the licence store), purchase links must be
    /// `https://`, and a `homepage` or `source` that is not `https://` is
    /// dropped (gen-catalogue copies the RPM's unchecked `URL` tag).
    pub fn parse(bytes: &[u8], arch: &str) -> Result<Self, CatalogueError> {
        let mut cat: Catalogue =
            serde_json::from_slice(bytes).map_err(|e| CatalogueError::Json(e.to_string()))?;
        if cat.schema != SCHEMA_VERSION {
            return Err(CatalogueError::UnsupportedSchema(cat.schema));
        }
        if cat.arch != arch {
            return Err(CatalogueError::WrongArch {
                expected: arch.into(),
                found: cat.arch,
            });
        }
        let mut names: Vec<&str> = cat.packages.iter().map(|p| p.name.as_str()).collect();
        names.sort_unstable();
        if let Some(w) = names.windows(2).find(|w| w[0] == w[1]) {
            return Err(CatalogueError::DuplicatePackage(w[0].to_string()));
        }
        for p in &mut cat.packages {
            p.category = display_category(&p.category);
            let invalid = |why: &str| CatalogueError::InvalidPackage {
                name: p.name.clone(),
                why: why.into(),
            };
            if let LicenceModel::OneOff {
                app_id,
                purchase_url,
            }
            | LicenceModel::Subscription {
                app_id,
                purchase_url,
            } = &p.licence
            {
                if !reef_licence::handoff::valid_app_id(app_id) {
                    return Err(invalid("licence app_id is not a valid app id"));
                }
                if !is_https_url(purchase_url) {
                    return Err(invalid("purchase_url is not an https:// URL"));
                }
            }
            for link in [&mut p.homepage, &mut p.source] {
                if link.as_deref().is_some_and(|u| !is_https_url(u)) {
                    *link = None;
                }
            }
            if p.icon.as_deref().is_some_and(|s| !is_asset_path(s)) {
                p.icon = None;
            }
            p.screenshots.retain(|s| is_asset_path(s));
            p.screenshots.truncate(MAX_SCREENSHOTS);
            if p.added.as_deref().is_some_and(|d| parse_date(d).is_none()) {
                p.added = None;
            }
        }
        let packages = &cat.packages;
        let mut seen = std::collections::HashSet::new();
        cat.featured
            .retain(|n| packages.iter().any(|p| &p.name == n) && seen.insert(n.clone()));
        Ok(cat)
    }

    /// The featured packages that are visible on this release, in the
    /// catalogue's order.
    pub fn featured_visible(&self, release: &SailfishRelease) -> Vec<&Package> {
        let visible = self.visible(release);
        self.featured
            .iter()
            .filter_map(|n| visible.iter().find(|p| &p.name == n).copied())
            .collect()
    }

    /// Packages tested on exactly this release, sorted by category and then
    /// title (the store's list has a section per category, and a `ListView`
    /// needs its model sorted by section). Everything else is hidden: a
    /// package tested on 5.2.0.17 is not shown on 5.2.0.18 until it has been
    /// re-tested there.
    pub fn visible(&self, release: &SailfishRelease) -> Vec<&Package> {
        let full = release.full();
        let mut out: Vec<&Package> = self
            .packages
            .iter()
            .filter(|p| p.tested_on.contains(&full))
            .collect();
        // `category` was normalised by `parse`, so the sort and the list's
        // sections (which compare the raw string) agree.
        out.sort_by_cached_key(|p| (p.category.clone(), p.title.to_lowercase(), p.name.clone()));
        out
    }

    /// Looks up a visible package by RPM name.
    pub fn visible_package(&self, name: &str, release: &SailfishRelease) -> Option<&Package> {
        self.visible(release).into_iter().find(|p| p.name == name)
    }
}

/// The one display form of a category: trimmed, first letter upper case and
/// the rest lower case, `Other` when empty. "audio" and " Audio" are the same
/// section.
pub fn display_category(raw: &str) -> String {
    let mut chars = raw.trim().chars();
    match chars.next() {
        None => default_category(),
        Some(first) => first
            .to_uppercase()
            .chain(chars.flat_map(char::to_lowercase))
            .collect(),
    }
}

/// A repository-relative path of an icon or screenshot: one or more
/// segments of `[A-Za-z0-9._-]`, none `.` or `..`, ending in `.png`, `.jpg`
/// or `.jpeg` (the formats every Qt build decodes), at most 200 bytes.
/// Never a URL, never absolute, so the client only ever fetches from the
/// repository it is pinned to.
pub fn is_asset_path(path: &str) -> bool {
    let ok_segment = |s: &str| {
        !s.is_empty()
            && s != "."
            && s != ".."
            && s.bytes()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, b'.' | b'_' | b'-'))
    };
    let lower = path.to_ascii_lowercase();
    path.len() <= 200
        && path.split('/').all(ok_segment)
        && [".png", ".jpg", ".jpeg"]
            .iter()
            .any(|ext| lower.ends_with(ext))
}

/// `YYYY-MM-DD` as days since 1970-01-01, or `None` when malformed.
pub fn parse_date(s: &str) -> Option<i64> {
    if s.len() != 10
        || !s.bytes().enumerate().all(|(i, c)| {
            if i == 4 || i == 7 {
                c == b'-'
            } else {
                c.is_ascii_digit()
            }
        })
    {
        return None;
    }
    let y: i64 = s[0..4].parse().ok()?;
    let m: i64 = s[5..7].parse().ok()?;
    let d: i64 = s[8..10].parse().ok()?;
    if !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return None;
    }
    // Howard Hinnant's days_from_civil.
    let y = if m <= 2 { y - 1 } else { y };
    let era = y.div_euclid(400);
    let yoe = y - era * 400;
    let mp = (m + 9) % 12;
    let doy = (153 * mp + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    Some(era * 146_097 + doe - 719_468)
}

/// An absolute `https://` URL with a host and no whitespace or control
/// characters: the only links the client opens.
pub fn is_https_url(url: &str) -> bool {
    url.strip_prefix("https://")
        .is_some_and(|rest| !rest.is_empty() && !rest.starts_with('/'))
        && url.len() <= 2048
        && !url.chars().any(|c| c.is_whitespace() || c.is_control())
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    pub const SAMPLE: &str = r#"{
      "schema": 1,
      "release": "5.2.0.17",
      "arch": "aarch64",
      "generated_at": "2026-09-30T12:00:00Z",
      "packages": [
        {
          "name": "shipwright-shoal-bridge-airpods-ui",
          "version": "1.0.0-1",
          "title": "Shoal Bridge",
          "summary": "AirPods battery, ear detection and listening modes",
          "category": "Audio",
          "tested_on": ["5.2.0.17", "5.2.0.18"],
          "permissions": ["Bluetooth", "Audio"],
          "keel_tier": "B",
          "licence": {"model": "one_off", "app_id": "shoal-bridge", "purchase_url": "https://shipwright.example/buy/shoal-bridge"}
        },
        {
          "name": "shipwright-keel-silica",
          "version": "0.1.0-1",
          "title": "Keel",
          "summary": "Silica for Qt6",
          "category": "Libraries",
          "tested_on": ["5.2.0.17"],
          "licence": {"model": "free"}
        },
        {
          "name": "shipwright-shoal-mail",
          "version": "0.9.0-1",
          "title": "Shoal Mail",
          "summary": "Mail",
          "tested_on": ["5.1.0.11"],
          "licence": {"model": "free"}
        }
      ]
    }"#;

    fn rel(s: &str) -> SailfishRelease {
        SailfishRelease::parse(s).unwrap()
    }

    #[test]
    fn parses_sample_with_defaults() {
        let cat = Catalogue::parse(SAMPLE.as_bytes(), "aarch64").unwrap();
        assert_eq!(cat.packages.len(), 3);
        let keel = &cat.packages[1];
        assert!(keel.sandboxed);
        assert_eq!(keel.licence, LicenceModel::Free);
        assert_eq!(cat.packages[2].category, "Other");
        assert_eq!(cat.packages[0].licence.app_id(), Some("shoal-bridge"));
        assert_eq!(cat.packages[0].keel_tier.as_deref(), Some("B"));
        assert_eq!(keel.keel_tier, None);
    }

    #[test]
    fn keel_tier_is_optional_and_open_ended() {
        // A catalogue from before the field existed still loads.
        let old = r#"{"schema":1,"release":"5.2.0.17","arch":"aarch64","packages":[
            {"name":"a","version":"1-1","title":"A","summary":"s","tested_on":["5.2.0.17"],
             "licence":{"model":"free"}}]}"#;
        let cat = Catalogue::parse(old.as_bytes(), "aarch64").unwrap();
        assert_eq!(cat.packages[0].keel_tier, None);
        // Every value the portal writes today, and a future one, parse.
        for tier in ["A", "B", "none", "not-applicable", "C"] {
            let json = old.replace(
                r#""licence":{"model":"free"}"#,
                &format!(r#""licence":{{"model":"free"}},"keel_tier":"{tier}""#),
            );
            let cat = Catalogue::parse(json.as_bytes(), "aarch64").unwrap();
            assert_eq!(cat.packages[0].keel_tier.as_deref(), Some(tier));
        }
        // Explicit null is the same as absent; a non-string is an error.
        let null = old.replace(
            r#""licence":{"model":"free"}"#,
            r#""licence":{"model":"free"},"keel_tier":null"#,
        );
        assert_eq!(
            Catalogue::parse(null.as_bytes(), "aarch64")
                .unwrap()
                .packages[0]
                .keel_tier,
            None
        );
        let number = old.replace(
            r#""licence":{"model":"free"}"#,
            r#""licence":{"model":"free"},"keel_tier":2"#,
        );
        assert!(matches!(
            Catalogue::parse(number.as_bytes(), "aarch64"),
            Err(CatalogueError::Json(_))
        ));
        // Round trip keeps it.
        let cat = Catalogue::parse(SAMPLE.as_bytes(), "aarch64").unwrap();
        let again = Catalogue::parse(&serde_json::to_vec(&cat).unwrap(), "aarch64").unwrap();
        assert_eq!(again, cat);
    }

    #[test]
    fn hides_untested_packages() {
        let cat = Catalogue::parse(SAMPLE.as_bytes(), "aarch64").unwrap();
        let names = |r: &str| -> Vec<String> {
            cat.visible(&rel(r))
                .iter()
                .map(|p| p.name.clone())
                .collect()
        };
        // Category (Audio, Libraries) first, then title.
        assert_eq!(
            names("5.2.0.17"),
            [
                "shipwright-shoal-bridge-airpods-ui",
                "shipwright-keel-silica"
            ]
        );
        assert_eq!(names("5.2.0.18"), ["shipwright-shoal-bridge-airpods-ui"]);
        assert_eq!(names("5.1.0.11"), ["shipwright-shoal-mail"]);
        assert!(names("5.2.0.19").is_empty());
        assert!(cat
            .visible_package("shipwright-shoal-mail", &rel("5.2.0.17"))
            .is_none());
    }

    #[test]
    fn sorted_by_category_then_title() {
        // U-01: titles interleave across categories; sections must not.
        let entry = |name: &str, title: &str, category: &str| {
            format!(
                r#"{{"name":"{name}","version":"1-1","title":"{title}","summary":"s",
                    "category":"{category}","tested_on":["5.2.0.17"],
                    "licence":{{"model":"free"}}}}"#
            )
        };
        let json = format!(
            r#"{{"schema":1,"release":"5.2.0.17","arch":"aarch64","packages":[{}]}}"#,
            [
                entry("a", "Zebra", "Audio"),
                entry("b", "apple", "Office"),
                entry("c", "Mango", "Audio"),
                entry("d", "Banana", "Office"),
                entry("e", "Cherry", "audio"),
                entry("f", "Date", " AUDIO "),
            ]
            .join(",")
        );
        let cat = Catalogue::parse(json.as_bytes(), "aarch64").unwrap();
        let rows: Vec<(&str, &str)> = cat
            .visible(&rel("5.2.0.17"))
            .iter()
            .map(|p| (p.category.as_str(), p.title.as_str()))
            .collect();
        assert_eq!(
            rows,
            [
                ("Audio", "Cherry"),
                ("Audio", "Date"),
                ("Audio", "Mango"),
                ("Audio", "Zebra"),
                ("Office", "apple"),
                ("Office", "Banana"),
            ]
        );
    }

    #[test]
    fn untrusted_fields_are_checked() {
        // B-03: the licence app id becomes a file name in the licence store.
        for bad in ["../../.config/x", ".hidden", "a/b", ""] {
            let json = SAMPLE.replace(
                "\"app_id\": \"shoal-bridge\"",
                &format!("\"app_id\": \"{bad}\""),
            );
            assert!(
                matches!(
                    Catalogue::parse(json.as_bytes(), "aarch64"),
                    Err(CatalogueError::InvalidPackage { .. })
                ),
                "{bad}"
            );
        }
        // U-03: only https purchase links; other links are dropped.
        let json = SAMPLE.replace(
            "https://shipwright.example/buy/shoal-bridge",
            "javascript:alert(1)",
        );
        assert!(matches!(
            Catalogue::parse(json.as_bytes(), "aarch64"),
            Err(CatalogueError::InvalidPackage { .. })
        ));
        let json = SAMPLE.replace(
            "\"keel_tier\": \"B\",",
            "\"keel_tier\": \"B\", \"homepage\": \"http://tracker.example/\", \"source\": \"https://git.example/x\",",
        );
        let cat = Catalogue::parse(json.as_bytes(), "aarch64").unwrap();
        assert_eq!(cat.packages[0].homepage, None);
        assert_eq!(
            cat.packages[0].source.as_deref(),
            Some("https://git.example/x")
        );
        for (url, ok) in [
            ("https://example.org/x", true),
            ("http://example.org/", false),
            ("https:///etc/passwd", false),
            ("file:///etc/passwd", false),
            ("https://a.example/ b", false),
            ("HTTPS://example.org", false),
        ] {
            assert_eq!(is_https_url(url), ok, "{url}");
        }
    }

    #[test]
    fn assets_publisher_added_and_featured() {
        for (p, ok) in [
            ("assets/shoal-mail.png", true),
            ("assets/shots/mail-1.jpg", true),
            ("assets/shots/mail-1.webp", false),
            ("ICON.PNG", true),
            ("https://example.org/x.png", false),
            ("/etc/passwd.png", false),
            ("assets/../../x.png", false),
            ("assets/./x.png", false),
            ("assets/x.svg", false),
            ("assets/x y.png", false),
            ("", false),
        ] {
            assert_eq!(is_asset_path(p), ok, "{p}");
        }
        assert_eq!(parse_date("1970-01-01"), Some(0));
        assert_eq!(parse_date("2000-02-29"), Some(11_016));
        assert_eq!(parse_date("2026-10-03"), Some(20_729));
        for bad in [
            "2026-13-01",
            "2026-1-01",
            "20261001",
            "2026-10-0a",
            "+026-10-01",
        ] {
            assert_eq!(parse_date(bad), None, "{bad}");
        }

        let json = SAMPLE
            .replace(
                "\"keel_tier\": \"B\",",
                r#""keel_tier": "B", "icon": "assets/bridge.png", "publisher": "Shipwright",
                   "added": "2026-10-01",
                   "screenshots": ["assets/shots/b1.jpg", "https://x/y.png", "assets/shots/b2.jpeg"],"#,
            )
            .replace(
                "\"summary\": \"Silica for Qt6\",",
                "\"summary\": \"Silica for Qt6\", \"icon\": \"http://x/k.png\", \"added\": \"soon\",",
            )
            .replace(
                "\"packages\": [",
                "\"featured\": [\"shipwright-keel-silica\", \"nope\", \"shipwright-shoal-mail\", \"shipwright-keel-silica\"], \"packages\": [",
            );
        let cat = Catalogue::parse(json.as_bytes(), "aarch64").unwrap();
        let bridge = &cat.packages[0];
        assert_eq!(bridge.icon.as_deref(), Some("assets/bridge.png"));
        assert_eq!(bridge.publisher, "Shipwright");
        assert_eq!(bridge.added.as_deref(), Some("2026-10-01"));
        assert_eq!(
            bridge.screenshots,
            ["assets/shots/b1.jpg", "assets/shots/b2.jpeg"]
        );
        let keel = &cat.packages[1];
        assert_eq!(keel.icon, None, "a URL is not an asset path");
        assert_eq!(keel.added, None);
        assert_eq!(keel.publisher, "");
        // Unknown and repeated names dropped; order kept.
        assert_eq!(
            cat.featured,
            ["shipwright-keel-silica", "shipwright-shoal-mail"]
        );
        // Mail is not tested on 5.2.0.17, so only Keel is featured there.
        let f: Vec<&str> = cat
            .featured_visible(&rel("5.2.0.17"))
            .iter()
            .map(|p| p.name.as_str())
            .collect();
        assert_eq!(f, ["shipwright-keel-silica"]);
        // Old catalogues without any of this still load.
        let old = Catalogue::parse(SAMPLE.as_bytes(), "aarch64").unwrap();
        assert!(old.featured.is_empty());
        assert!(old.packages[0].screenshots.is_empty());
    }

    #[test]
    fn rejects_bad_catalogues() {
        assert!(matches!(
            Catalogue::parse(SAMPLE.as_bytes(), "armv7hl"),
            Err(CatalogueError::WrongArch { .. })
        ));
        let v2 = SAMPLE.replace("\"schema\": 1", "\"schema\": 2");
        assert_eq!(
            Catalogue::parse(v2.as_bytes(), "aarch64"),
            Err(CatalogueError::UnsupportedSchema(2))
        );
        let dup = SAMPLE.replace("shipwright-shoal-mail", "shipwright-keel-silica");
        assert!(matches!(
            Catalogue::parse(dup.as_bytes(), "aarch64"),
            Err(CatalogueError::DuplicatePackage(_))
        ));
        let bad_model = SAMPLE.replace("\"model\": \"free\"", "\"model\": \"freemium\"");
        assert!(matches!(
            Catalogue::parse(bad_model.as_bytes(), "aarch64"),
            Err(CatalogueError::Json(_))
        ));
    }
}
