// Modified by Shipwright, 2026: rebranded as Shoal Messages; see CHANGES-FROM-UPSTREAM.md.
.pragma library


.import "Emoji.js" as Emoji
// Shared by the room timeline and the thread view, which draw the same rows.

// The core's markup, adjusted for the web-link setting and for the one thing
// the renderer cannot do. Every tag in it was generated by `markup.rs`, so a
// pattern over it is safe - nothing else in this app writes a `<`.
function renderFormatted(markup, clickableLinks, codeColour) {
    // `<code>` is our own marker, not a tag Qt knows. Qt's `<font>` takes only
    // `color` and `size`, so an inline monospace font is out of reach and the
    // colour has to carry the meaning. Left alone it renders as bare text.
    var out = markup.replace(/<code>([\s\S]*?)<\/code>/g, function(all, text) {
        return '<font color="' + codeColour + '">' + text + '</font>'
    })
    if (clickableLinks) {
        return out
    }
    markup = out
    // Anchors never nest - `markup.rs` refuses that - so a whole anchor matches at
    // once. A Matrix permalink keeps its target: it never reaches a browser.
    return markup.replace(/<a href="([^"]*)">([\s\S]*?)<\/a>/g,
                          function(anchor, href, text) {
        var internal = /^https?:\/\/(www\.)?matrix\.to\/#\//i.test(href)
                       || href.indexOf("matrix:") === 0
                       || href.indexOf("shoal-messages:") === 0
        return internal ? anchor : text
    })
}

// Emoji drawn as the user's own pictures. The text must already be escaped:
// this inserts `<img>` tags, and the provider refuses a name it did not write.
var _sequences = null
var _longest = 0

function _dictionary() {
    if (_sequences) {
        return _sequences
    }
    _sequences = {}
    for (var g = 0; g < Emoji.groups.length; g++) {
        var items = Emoji.groups[g].items
        for (var i = 0; i < items.length; i++) {
            _sequences[items[i]] = true
            if (items[i].length > _longest) {
                _longest = items[i].length
            }
        }
    }
    return _sequences
}

/// Replaces every emoji that has a picture. Unchanged text is how the caller
/// decides whether the row needs the markup renderer at all.
function withEmojiPictures(escaped, size, source) {
    if (!escaped || escaped.length === 0) {
        return escaped
    }
    var known = _dictionary()
    var out = ""
    var i = 0
    var replaced = false
    var inTag = false
    while (i < escaped.length) {
        var here = escaped.charAt(i)
        // Tags are skipped whole: the text was escaped first, so every `<` was written
        // by this app - and an `<img>` inside an attribute breaks that tag.
        if (here === "<") {
            inTag = true
        } else if (here === ">") {
            inTag = false
        }
        if (inTag) {
            out += here
            i += 1
            continue
        }
        var code = escaped.charCodeAt(i)
        // Cheap gate: everything below the symbol blocks is ordinary text, and
        // a message is mostly ordinary text.
        if (code < 0x203C) {
            out += escaped.charAt(i)
            i += 1
            continue
        }
        var hit = ""
        var max = Math.min(_longest, escaped.length - i)
        for (var len = max; len > 0; len--) {
            var candidate = escaped.substr(i, len)
            if (known[candidate]) {
                hit = candidate
                break
            }
        }
        if (hit.length === 0) {
            out += escaped.charAt(i)
            i += 1
            continue
        }
        var picture = source(hit)
        if (picture.length === 0) {
            out += hit
            i += hit.length
            continue
        }
        out += '<img src="' + picture + '" width="' + size + '" height="' + size + '">'
        i += hit.length
        replaced = true
    }
    return replaced ? out : escaped
}
