// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: MIT-0

//! The CXX-Qt bridge: the `Greeter` QML singleton (`import {{qml_uri}} 1.0`)
//! over [`crate::greeter::Greeter`], and the C++ launcher.

#![allow(
    clippy::unnecessary_box_returns,
    reason = "the constructor is generated by cxx_qt::bridge"
)]

#[cxx_qt::bridge]
pub mod qobject {
    unsafe extern "C++" {
        include!("cxx-qt-lib/qstring.h");
        type QString = cxx_qt_lib::QString;
    }

    unsafe extern "C++" {
        include!("{{name}}/cpp/launcher.h");
        /// Creates the application and the SailfishApp view, loads the main
        /// QML file and runs the event loop. Returns the exit status.
        fn keel_app_run(args: &Vec<String>) -> i32;
        /// The app's command line (Keel's launcher; also right when
        /// booster-keel runs the app, where `std::env::args()` is not).
        fn keel_launch_arguments() -> Vec<String>;
    }

    extern "RustQt" {
        #[qobject]
        #[qml_element]
        #[qml_singleton]
        #[qproperty(i32, count, READ, NOTIFY)]
        #[qproperty(QString, summary, READ, NOTIFY)]
        type Greeter = super::GreeterRust;

        /// Adds a greeting.
        #[qinvokable]
        fn increment(self: Pin<&mut Greeter>);

        /// Removes all greetings.
        #[qinvokable]
        fn reset(self: Pin<&mut Greeter>);

        /// The text of list row `index`; empty outside the list.
        #[qinvokable]
        fn line(self: &Greeter, index: i32) -> QString;
    }
}

use core::pin::Pin;

use cxx_qt::CxxQtType;
use cxx_qt_lib::QString;

use crate::greeter::Greeter;

/// The Rust side of the `Greeter` `QObject`.
pub struct GreeterRust {
    count: i32,
    summary: QString,
    model: Greeter,
}

impl Default for GreeterRust {
    fn default() -> Self {
        let model = Greeter::default();
        Self {
            count: i32::try_from(model.count()).unwrap_or(i32::MAX),
            summary: QString::from(model.summary().as_str()),
            model,
        }
    }
}

impl qobject::Greeter {
    /// Copies the model's state into the properties and notifies QML of
    /// what changed.
    fn sync(mut self: Pin<&mut Self>) {
        let count = i32::try_from(self.model.count()).unwrap_or(i32::MAX);
        let summary = QString::from(self.model.summary().as_str());
        if self.count != count {
            self.as_mut().rust_mut().count = count;
            self.as_mut().count_changed();
        }
        if self.summary != summary {
            self.as_mut().rust_mut().summary = summary;
            self.as_mut().summary_changed();
        }
    }

    fn increment(mut self: Pin<&mut Self>) {
        self.as_mut().rust_mut().model.increment();
        self.sync();
    }

    fn reset(mut self: Pin<&mut Self>) {
        self.as_mut().rust_mut().model.reset();
        self.sync();
    }

    fn line(&self, index: i32) -> QString {
        match u32::try_from(index) {
            Ok(i) if i < self.model.count() => QString::from(Greeter::line(i).as_str()),
            _ => QString::default(),
        }
    }
}
