#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Patrick Quinn
# SPDX-License-Identifier: MIT
"""Engineering English of every qsTrId() in sailfish-components-webview's QML
(the `//%` comment before it; popups/, pickers/, controls/ and the
WebView itself, qml/, here) as a C++
table for Keel's fallback translator (webengine/webviewstrings.inc), as
keel/silica/upstream/port.py does for Silica. Sailfish ships the compiled
catalogues; Keel has none, so without the table dialogs would show ids.

    python3 keel/platform/webview/strings.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
table = {}
for sub in ("popups", "pickers", "controls", "qml"):
    for name in sorted(os.listdir(os.path.join(HERE, sub))):
        if not name.endswith((".qml", ".js")):
            continue
        pending = None
        for line in open(os.path.join(HERE, sub, name), encoding="utf-8").read().splitlines():
            m = re.search(r'//%\s*"((?:[^"\\]|\\.)*)"', line)
            if m:
                pending = m.group(1)
            for tid in re.findall(r'qsTrId\("([^"]+)"', line):
                if pending is not None:
                    table.setdefault(tid, pending)
                pending = None
out = [
    # REUSE-IgnoreStart
    "// Generated by keel/platform/webview/strings.py from the //% comments in",
    "// sailfish-components-webview's QML (popups, pickers, controls). Do not edit.",
    "// SPDX-FileCopyrightText: 2013-2026 Jolla Ltd.",
    "// SPDX-FileCopyrightText: 2019-2021 Open Mobile Platform LLC",
    "// SPDX-License-Identifier: MPL-2.0",
    # REUSE-IgnoreEnd
]
for tid in sorted(table):
    out.append('{ "%s", "%s" },' % (tid, table[tid]))
path = os.path.join(HERE, "..", "webengine", "webviewstrings.inc")
open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("%d strings -> %s" % (len(table), os.path.relpath(path, HERE)))
