# SPDX-FileCopyrightText: 2026 Patrick Quinn
# SPDX-License-Identifier: MIT-0
#
# {{title}}: Rust (CXX-Qt) app on Keel (direct mode on Lipstick, started in
# its own booster, booster-keel@{{name}}), sandboxed by Sailjail.
#
# Shipwright SDK convention (tools/build/sdk/README.md in Shipwright): no
# cargo in the spec. Cross-build the app first with Shipwright's
# tools/build/sdk/cxxqt-sailfish.sh, so it lands at
#     target/aarch64-unknown-linux-gnu/release/lib{{crate}}.so
# (a shared library that is also executable, installed as /usr/bin/{{name}};
# see build.rs)
# (or pass --define "app_bin <path>"); rpm/build-in-sdk.sh does both steps.
# By hand, inside the Sailfish SDK, from this directory:
#     mb2 -t SailfishOS-5.2.0.15-aarch64 --snapshot={{name}} \
#         -s rpm/{{name}}.spec build

%global app {{name}}
%{!?app_bin: %global app_bin target/%{_arch}-unknown-linux-gnu/release/lib{{crate}}.so}
%global debug_package %{nil}
%global _build_id_links none

Name:           {{name}}
Version:        0.1.0
Release:        1
Summary:        {{summary}}
License:        {{license}}
URL:            https://example.invalid/{{name}}

# Runtime: Keel (Sailfish.Silica for Qt 6), its SailfishApp library and
# launcher, and Chum Qt 6. Qt's own libraries come from automatic
# dependencies.
Requires:       shipwright-keel-silica
Requires:       shipwright-keel-sailfishapp
# The app starts in its own booster, booster-keel@{{name}}, through
# `invoker --type=keel -A` in its desktop file; keel-shell is the opt-in
# fallback window path.
Requires:       shipwright-keel-booster
Recommends:     shipwright-keel-shell
Requires:       qt6-qtdeclarative

BuildRequires:  desktop-file-utils

%description
{{summary}}. A Sailfish OS app with a Rust core and a Silica user
interface on Keel (Qt 6).

%prep

%build

%install
if [ ! -x %{app_bin} ]; then
    echo "%{app_bin} is missing: cross-build it first (rpm/build-in-sdk.sh)" >&2
    exit 1
fi
install -D -m 0755 %{app_bin} %{buildroot}%{_bindir}/%{app}
install -d %{buildroot}%{_datadir}/%{app}
cp -R qml %{buildroot}%{_datadir}/%{app}/qml
install -D -m 0644 packaging/%{app}.desktop \
    %{buildroot}%{_datadir}/applications/%{app}.desktop
desktop-file-validate %{buildroot}%{_datadir}/applications/%{app}.desktop
# The app's own booster (booster-keel@%{app}, inside its sandbox) starts
# with the session; the desktop file reaches it with `invoker --type=keel -A`.
mkdir -p %{buildroot}%{_prefix}/lib/systemd/user/user-session.target.d
printf '[Unit]\nWants=booster-keel@%s.service\n' %{app} \
    > %{buildroot}%{_prefix}/lib/systemd/user/user-session.target.d/50-%{app}.conf
# Launcher icons, rendered from icons/%{app}.svg by icons/render-icons.sh.
for s in 86 108 128 172; do
    install -D -m 0644 icons/hicolor/${s}x${s}/apps/%{app}.png \
        %{buildroot}%{_datadir}/icons/hicolor/${s}x${s}/apps/%{app}.png
done
# An app that defines its own Sailjail permission ships it like this, and
# lists it in %%files as %%config(noreplace):
#   install -D -m 0644 packaging/{{pascal}}.permission \
#       %%{buildroot}%%{_sysconfdir}/sailjail/permissions/{{pascal}}.permission

%post
# The app's booster, started now rather than at the next session: the
# desktop file's `invoker -A` starts nothing without it.
systemctl-user daemon-reload >/dev/null 2>&1 || :
systemctl-user restart booster-keel@%{app}.service >/dev/null 2>&1 || :

%preun
if [ $1 -eq 0 ]; then
    systemctl-user stop booster-keel@%{app}.service >/dev/null 2>&1 || :
fi

%postun
systemctl-user daemon-reload >/dev/null 2>&1 || :

%files
%license LICENSES/{{license}}.txt
%{_bindir}/%{app}
%{_datadir}/%{app}
%{_datadir}/applications/%{app}.desktop
%{_prefix}/lib/systemd/user/user-session.target.d/50-%{app}.conf
%{_datadir}/icons/hicolor/*/apps/%{app}.png
# %%config(noreplace) %%{_sysconfdir}/sailjail/permissions/{{pascal}}.permission

%changelog
* {{changelog_date}} {{copyright}} - 0.1.0-1
- First package, generated by keel new.
