// Generated by `keel actions` as a starting point; edit it freely (it is
// only written when missing). Include it from src/lib.rs:
//
//     #[cfg(test)]
//     #[path = "<tests dir>/keel_actions_tests.rs"]
//     mod keel_actions_tests;
//
// It needs keel-actions-schema as a dev-dependency and keel::manifest!()
// in the crate.

use keel_actions_schema::validate::validate;
use serde_json::{json, Value};

fn tool(action: &str) -> Value {
    let manifest: Value = serde_json::from_str(keel::manifest_json().expect("keel::manifest!()")).unwrap();
    let name = format!("{}/{action}", manifest["appId"].as_str().unwrap());
    manifest["tools"].as_array().unwrap().iter().find(|t| t["name"] == name.as_str()).cloned().expect("declared")
}

#[test]
fn notes_search_schema() {
    let input = &tool("notes.search")["inputSchema"];
    validate(input, &json!({"query":"x"})).unwrap();
    assert!(validate(input, &json!({})).is_err());
    assert!(validate(input, &json!({"query":"x","unexpected":1})).is_err());
}

#[test]
fn notes_search_invoke() {
    let result = keel::invoke("notes.search", json!({"query":"x"})).expect("registered").wait();
    if let Err(e) = &result {
        assert_ne!(e.code, keel::ErrorCode::InvalidArguments, "{e}");
    }
    // TODO: check the result (or the effect of the action).
}

#[test]
fn notes_delete_schema() {
    let input = &tool("notes.delete")["inputSchema"];
    validate(input, &json!({"note":"keel://org.example.rustnotes/note/example"})).unwrap();
    assert!(validate(input, &json!({})).is_err());
    assert!(validate(input, &json!({"note":"keel://org.example.rustnotes/note/example","unexpected":1})).is_err());
}

#[test]
#[ignore = "acts on real data or the network: run it against test data"]
fn notes_delete_invoke() {
    let result = keel::invoke("notes.delete", json!({"note":"keel://org.example.rustnotes/note/example"})).expect("registered").wait();
    if let Err(e) = &result {
        assert_ne!(e.code, keel::ErrorCode::InvalidArguments, "{e}");
    }
    // TODO: check the result (or the effect of the action).
}

#[test]
fn notes_touch_schema() {
    let input = &tool("notes.touch")["inputSchema"];
    validate(input, &json!({})).unwrap();
    assert!(validate(input, &json!({"unexpected":1})).is_err());
}

#[test]
fn notes_touch_invoke() {
    let result = keel::invoke("notes.touch", json!({})).expect("registered").wait();
    if let Err(e) = &result {
        assert_ne!(e.code, keel::ErrorCode::InvalidArguments, "{e}");
    }
    // TODO: check the result (or the effect of the action).
}

#[test]
fn notes_panic_schema() {
    let input = &tool("notes.panic")["inputSchema"];
    validate(input, &json!({})).unwrap();
    assert!(validate(input, &json!({"unexpected":1})).is_err());
}

#[test]
fn notes_panic_invoke() {
    let result = keel::invoke("notes.panic", json!({})).expect("registered").wait();
    if let Err(e) = &result {
        assert_ne!(e.code, keel::ErrorCode::InvalidArguments, "{e}");
    }
    // TODO: check the result (or the effect of the action).
}
