// Generated by `keel actions` as a starting point; edit it freely (it is
// only written when missing). Run it with qmltestrunner and
// KEEL_ACTIONS_APP_ID=org.example.notes (paths below assume this file sits in the
// tests directory given to `keel actions --tests`).
import QtQuick 2.15
import QtTest 1.2
import Keel.Actions 1.0

TestCase {
    name: "KeelActions"
    when: windowShown

    // The files that declare the actions. Replace a Loader with your own
    // set-up if the file needs more (models, singletons) to load.
    Loader { id: declarations0; source: "../../../../tests/app/NotesActions.qml" }

    function test_notes_create_schema() {
        compare(KeelActions.invoke("notes.create", {}).errorCode, "InvalidArguments")
        const tooLong = {"body":""}
        tooLong["body"] = "x".repeat(20001)
        compare(KeelActions.invoke("notes.create", tooLong).errorCode, "InvalidArguments")
        compare(KeelActions.invoke("notes.create", {"body":"x","unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_create_invoke() {
        const call = KeelActions.invoke("notes.create", {"body":"x"})
        tryCompare(call, "finished", true, 26000)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_notes_search_schema() {
        compare(KeelActions.invoke("notes.search", {}).errorCode, "InvalidArguments")
        const tooLong = {"query":""}
        tooLong["query"] = "x".repeat(257)
        compare(KeelActions.invoke("notes.search", tooLong).errorCode, "InvalidArguments")
        compare(KeelActions.invoke("notes.search", {"query":"x","unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_search_invoke() {
        const call = KeelActions.invoke("notes.search", {"query":"x"})
        tryCompare(call, "finished", true, 26000)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_notes_delete_schema() {
        compare(KeelActions.invoke("notes.delete", {}).errorCode, "InvalidArguments")
        compare(KeelActions.invoke("notes.delete", {"note":"keel://org.example.notes/note/example","unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_delete_invoke() {
        skip("notes.delete acts on real data or the network: run it against test data")
        const call = KeelActions.invoke("notes.delete", {"note":"keel://org.example.notes/note/example"})
        tryCompare(call, "finished", true, 26000)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_notes_share_schema() {
        compare(KeelActions.invoke("notes.share", {}).errorCode, "InvalidArguments")
        compare(KeelActions.invoke("notes.share", {"note":"keel://org.example.notes/note/example","to":"keel://org.example.contacts/contact/example","unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_share_invoke() {
        skip("notes.share acts on real data or the network: run it against test data")
        const call = KeelActions.invoke("notes.share", {"note":"keel://org.example.notes/note/example","to":"keel://org.example.contacts/contact/example"})
        tryCompare(call, "finished", true, 1200)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_notes_broken_schema() {
        compare(KeelActions.invoke("notes.broken", {"unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_broken_invoke() {
        const call = KeelActions.invoke("notes.broken", {})
        tryCompare(call, "finished", true, 26000)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_notes_later_schema() {
        compare(KeelActions.invoke("notes.later", {}).errorCode, "InvalidArguments")
        const tooLong = {"text":""}
        tooLong["text"] = "x".repeat(33)
        compare(KeelActions.invoke("notes.later", tooLong).errorCode, "InvalidArguments")
        compare(KeelActions.invoke("notes.later", {"text":"x","unexpected":1}).errorCode, "InvalidArguments")
    }

    function test_notes_later_invoke() {
        const call = KeelActions.invoke("notes.later", {"text":"x"})
        tryCompare(call, "finished", true, 26000)
        verify(call.errorCode !== "InvalidArguments", call.errorMessage)
        // TODO: check call.result (or the effect of the action).
    }

    function test_note_find() {
        const call = KeelActions.findEntities("note", "", 5)
        tryCompare(call, "finished", true, 26000)
        verify(call.succeeded, call.errorMessage)
        // TODO: look one up: KeelActions.getEntity("note", <id>)
    }
}
