#!/bin/bash
# Modified by Shipwright, 2026: rebranded as Shoal Messages; builds natively in a Sailfish OS root
# (SAILFISH_NATIVE=1) as well as with the SDK; see CHANGES-FROM-UPSTREAM.md.
# Cross-build the Rust core into a static library for the Sailfish target and
# regenerate the C header the Qt side includes.
#
# Rust is built on the host, not inside the SDK chroot: scratchbox2 and cargo
# do not get along. Because the crate is a `staticlib`, cargo never links —
# it only archives objects — so no cross linker is needed here. The C and
# assembly parts of the dependency tree (aws-lc-sys, bundled sqlite) do need a
# working compiler, which takes some coaxing:
#
#   * the SDK's cross gcc is a 32-bit binary whose cc1 loads libmpc/libmpfr/
#     libgmp from the tooling tree, not from the host, and
#   * it looks up an unprefixed `as`, so without help it finds the host
#     assembler and fails with "unknown option -EL".
#
# Both are handled by the generated wrapper below. The real link happens later
# in `mb2 build` against the device sysroot.
#
# Usage: scripts/build-core.sh [--debug]

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$HERE")"
# shellcheck source=sdk-env.sh
. "$HERE/sdk-env.sh"
sdk_env_check

# The core reports its own version via xm_version(), taken from Cargo.toml.
# That string once trailed the package version by eleven releases and sent a
# debugging round after the wrong build — so a mismatch stops the build here.
SPEC_VERSION="$(sed -n 's/^Version:[[:space:]]*//p' "$ROOT/rpm/shipwright-shoal-messages.spec")"
CARGO_VERSION="$(sed -n 's/^version = "\(.*\)"$/\1/p' "$ROOT/core/Cargo.toml" | head -1)"
if [ -z "$SPEC_VERSION" ] || [ -z "$CARGO_VERSION" ]; then
    echo "error: could not read the version from rpm/shipwright-shoal-messages.spec or core/Cargo.toml" >&2
    exit 1
fi
if [ "$SPEC_VERSION" != "$CARGO_VERSION" ]; then
    echo "error: version mismatch — rpm/shipwright-shoal-messages.spec says $SPEC_VERSION," >&2
    echo "       core/Cargo.toml says $CARGO_VERSION. Align both before building." >&2
    exit 1
fi

PROFILE=release
CARGO_PROFILE_FLAG=(--release)
if [ "${1:-}" = "--debug" ]; then
    PROFILE=debug
    CARGO_PROFILE_FLAG=()
fi

# Natively (tools/build/native) the target's gcc is the system's: no wrapper.
if [ "${SAILFISH_NATIVE:-0}" != 1 ]; then
# --- generated cross-compiler wrapper ---------------------------------------
SDK_BIN="$ROOT/core/target/sdk-bin"
TOOLING_LIB="${SAILFISH_SDK_ROOT}/toolings/SailfishOS-${SFOS_RELEASE}/usr/lib"
mkdir -p "$SDK_BIN"

# Unprefixed binutils so gcc's own lookup finds the cross tools first.
for tool in as ld ar ranlib nm objcopy objdump strip; do
    ln -sf "${SFOS_CROSS_BIN}/${SFOS_CROSS_PREFIX}-${tool}" "$SDK_BIN/$tool"
done

for lang in gcc g++; do
    cat > "$SDK_BIN/cross-$lang" <<EOF
#!/bin/bash
# Generated by scripts/build-core.sh — do not edit.
export LD_LIBRARY_PATH="${TOOLING_LIB}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export PATH="${SDK_BIN}:\$PATH"
exec "${SFOS_CROSS_BIN}/${SFOS_CROSS_PREFIX}-${lang}" --sysroot="${SFOS_SYSROOT}" "\$@"
EOF
    chmod +x "$SDK_BIN/cross-$lang"
done

TARGET_UPPER="$(echo "$RUST_TARGET" | tr 'a-z-' 'A-Z_')"
TARGET_UNDER="${RUST_TARGET//-/_}"

export "CC_${TARGET_UNDER}=${SDK_BIN}/cross-gcc"
export "CXX_${TARGET_UNDER}=${SDK_BIN}/cross-g++"
export "AR_${TARGET_UNDER}=${SFOS_CROSS_BIN}/${SFOS_CROSS_PREFIX}-ar"
export "CARGO_TARGET_${TARGET_UPPER}_LINKER=${SDK_BIN}/cross-gcc"
fi
TARGET_UNDER="${RUST_TARGET//-/_}"

# Rust embeds the source path of every crate into its panic messages, and the
# C parts do the same through __FILE__. Unremapped, the finished binary carries
# hundreds of strings naming the build machine's home directory — invisible to
# strip, and a plain identity leak in anything published.
export RUSTFLAGS="--remap-path-prefix=$HOME/.cargo/registry=/cargo \
--remap-path-prefix=$HOME/.rustup=/rustup \
--remap-path-prefix=$ROOT=/build ${RUSTFLAGS:-}"
sysroot_flag="--sysroot=${SFOS_SYSROOT} "
[ "${SAILFISH_NATIVE:-0}" = 1 ] && sysroot_flag=
export "CFLAGS_${TARGET_UNDER}=${sysroot_flag}\
-ffile-prefix-map=$HOME/.cargo/registry=/cargo -ffile-prefix-map=$ROOT=/build"

# The Sailfish SDK's rustup host is i686: rustc gets 4 GB of address space
# and runs out of memory ("rustc-LLVM ERROR: out of memory") optimising this
# crate as one codegen unit. Splitting it keeps thin LTO and fits.
if [ "$(rustc -vV | sed -n 's/^host: //p')" = i686-unknown-linux-gnu ]; then
    export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=${CARGO_PROFILE_RELEASE_CODEGEN_UNITS:-16}
fi

echo "→ cargo build ($PROFILE) for $RUST_TARGET"
cargo build "${CARGO_PROFILE_FLAG[@]}" \
    --target "$RUST_TARGET" \
    --manifest-path "$ROOT/core/Cargo.toml"

LIB="$ROOT/core/target/$RUST_TARGET/$PROFILE/libshoal_messages_core.a"
[ -f "$LIB" ] || { echo "error: expected $LIB to exist" >&2; exit 1; }

# Stamp the archive with the version it carries; the .pro refuses to link a
# stale core against a newer spec (the mb2-only half of the mismatch guard).
printf '%s\n' "$CARGO_VERSION" > "$LIB.version"

echo "→ cbindgen → src/generated/shoal_messages_core.h"
if ! command -v cbindgen >/dev/null; then
    echo "error: cbindgen not on PATH — install it with: cargo install cbindgen" >&2
    exit 1
fi
mkdir -p "$ROOT/src/generated"
cbindgen --quiet \
    --config "$ROOT/core/cbindgen.toml" \
    --crate shoal-messages-core \
    --output "$ROOT/src/generated/shoal_messages_core.h" \
    "$ROOT/core"

echo "→ done: $(du -h "$LIB" | cut -f1)  $LIB"
