// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: MIT

//! Per-action test stubs: a QML `TestCase` for actions declared in QML and
//! Rust unit tests for `#[keel::action]` functions. Each action gets a
//! schema round trip (a generated valid argument set; missing required
//! arguments, over-long strings and unknown arguments are rejected) and an
//! invocation. Stubs are a starting point for the developer and are only
//! written when missing.

use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use keel_actions_schema::decl::App;
use keel_actions_schema::example::example;
use serde_json::{Map, Value};

use crate::Artefact;

fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn tool<'a>(manifest: &'a Value, name: &str) -> Option<&'a Value> {
    manifest["tools"]
        .as_array()?
        .iter()
        .find(|t| t["name"].as_str() == Some(name))
}

/// The path of `target` relative to directory `from` (both as written,
/// made absolute against the current directory).
fn relative(target: &Path, from: &Path) -> PathBuf {
    let abs = |p: &Path| {
        let p = if p.is_absolute() {
            p.to_path_buf()
        } else {
            std::env::current_dir().unwrap_or_default().join(p)
        };
        let mut out = PathBuf::new();
        for c in p.components() {
            match c {
                Component::ParentDir => {
                    out.pop();
                }
                Component::CurDir => {}
                other => out.push(other),
            }
        }
        out
    };
    let (t, f) = (abs(target), abs(from));
    let common = t
        .components()
        .zip(f.components())
        .take_while(|(a, b)| a == b)
        .count();
    let mut out = PathBuf::new();
    for _ in f.components().skip(common) {
        out.push("..");
    }
    for c in t.components().skip(common) {
        out.push(c);
    }
    out
}

/// A string parameter with maxLength, for the over-long test.
fn long_string(input: &Value) -> Option<(String, u64)> {
    let props = input["properties"].as_object()?;
    props.iter().find_map(|(name, s)| {
        (s["type"] == "string" && s.get("pattern").is_none())
            .then(|| s["maxLength"].as_u64().map(|m| (name.clone(), m)))
            .flatten()
    })
}

fn js(value: &Value) -> String {
    serde_json::to_string(value).unwrap_or_default()
}

pub fn stubs(app: &App, manifest: &Value) -> Vec<Artefact> {
    let mut out = Vec::new();
    let qml_actions: Vec<_> = app.actions.iter().filter(|a| !a.native).collect();
    if !qml_actions.is_empty() || app.entities.iter().any(|e| !e.native) {
        out.push(qml_stub(app, manifest));
    }
    if app.actions.iter().any(|a| a.native) {
        out.push(rust_stub(app, manifest));
    }
    out
}

fn qml_stub(app: &App, manifest: &Value) -> Artefact {
    let mut files: Vec<String> = app
        .actions
        .iter()
        .filter(|a| !a.native)
        .map(|a| a.source.as_str())
        .chain(
            app.entities
                .iter()
                .filter(|e| !e.native)
                .map(|e| e.source.as_str()),
        )
        .map(|s| s.rsplit_once(':').map_or(s, |(f, _)| f).to_owned())
        .collect();
    files.sort();
    files.dedup();
    let mut s = format!(
        "// Generated by `keel actions` as a starting point; edit it freely (it is\n\
         // only written when missing). Run it with qmltestrunner and\n\
         // KEEL_ACTIONS_APP_ID={app_id} (paths below assume this file sits in the\n\
         // tests directory given to `keel actions --tests`).\n\
         import QtQuick 2.15\n\
         import QtTest 1.2\n\
         import Keel.Actions 1.0\n\n\
         TestCase {{\n    name: \"KeelActions\"\n    when: windowShown\n\n\
         \x20   // The files that declare the actions. Replace a Loader with your own\n\
         \x20   // set-up if the file needs more (models, singletons) to load.\n",
        app_id = app.app_id
    );
    for (i, f) in files.iter().enumerate() {
        let _ = writeln!(
            s,
            "    Loader {{ id: declarations{i}; source: \"@TESTS@/{f}\" }}"
        );
    }
    for a in app.actions.iter().filter(|a| !a.native) {
        let Some(t) = tool(manifest, &format!("{}/{}", app.app_id, a.name)) else {
            continue;
        };
        let input = &t["inputSchema"];
        let (args, unsatisfied) = example(input);
        let id = ident(&a.name);
        let _ = writeln!(s, "\n    function test_{id}_schema() {{");
        if input["required"].as_array().is_some_and(|r| !r.is_empty()) {
            let _ = writeln!(
                s,
                "        compare(KeelActions.invoke(\"{}\", {{}}).errorCode, \"InvalidArguments\")",
                a.name
            );
        }
        if let Some((name, max)) = long_string(input) {
            let mut long = args.as_object().cloned().unwrap_or_default();
            long.insert(name.clone(), Value::String(String::new()));
            let _ = writeln!(
                s,
                "        const tooLong = {}\n        tooLong[\"{name}\"] = \"x\".repeat({})\n        compare(KeelActions.invoke(\"{}\", tooLong).errorCode, \"InvalidArguments\")",
                js(&Value::Object(long)),
                max + 1,
                a.name
            );
        }
        let mut extra = args.as_object().cloned().unwrap_or_default();
        extra.insert("unexpected".into(), Value::from(1));
        let _ = writeln!(
            s,
            "        compare(KeelActions.invoke(\"{}\", {}).errorCode, \"InvalidArguments\")\n    }}",
            a.name,
            js(&Value::Object(extra))
        );
        let _ = writeln!(s, "\n    function test_{id}_invoke() {{");
        if a.destructive || a.open_world || a.confirm {
            let _ = writeln!(
                s,
                "        skip(\"{} acts on real data or the network: run it against test data\")",
                a.name
            );
        }
        for p in &unsatisfied {
            let _ = writeln!(s, "        // TODO: {p} must match its pattern.");
        }
        let _ = writeln!(
            s,
            "        const call = KeelActions.invoke(\"{}\", {})\n        tryCompare(call, \"finished\", true, {})\n        verify(call.errorCode !== \"InvalidArguments\", call.errorMessage)\n        // TODO: check call.result (or the effect of the action).\n    }}",
            a.name,
            js(&args),
            a.timeout_ms + 1000
        );
    }
    for e in app.entities.iter().filter(|e| !e.native) {
        let _ = writeln!(
            s,
            "\n    function test_{t}_find() {{\n        const call = KeelActions.findEntities(\"{t}\", \"\", 5)\n        tryCompare(call, \"finished\", true, 26000)\n        verify(call.succeeded, call.errorMessage)\n        // TODO: look one up: KeelActions.getEntity(\"{t}\", <id>)\n    }}",
            t = e.type_name
        );
    }
    s.push_str("}\n");
    Artefact {
        name: "tst_keel_actions.qml".into(),
        contents: s,
    }
}

fn rust_stub(app: &App, manifest: &Value) -> Artefact {
    let mut s = String::from(
        "// Generated by `keel actions` as a starting point; edit it freely (it is\n\
         // only written when missing). Include it from src/lib.rs:\n\
         //\n\
         //     #[cfg(test)]\n\
         //     #[path = \"<tests dir>/keel_actions_tests.rs\"]\n\
         //     mod keel_actions_tests;\n\
         //\n\
         // It needs keel-actions-schema as a dev-dependency and keel::manifest!()\n\
         // in the crate.\n\n\
         use keel_actions_schema::validate::validate;\n\
         use serde_json::{json, Value};\n\n\
         fn tool(action: &str) -> Value {\n\
         \x20   let manifest: Value = serde_json::from_str(keel::manifest_json().expect(\"keel::manifest!()\")).unwrap();\n\
         \x20   let name = format!(\"{}/{action}\", manifest[\"appId\"].as_str().unwrap());\n\
         \x20   manifest[\"tools\"].as_array().unwrap().iter().find(|t| t[\"name\"] == name.as_str()).cloned().expect(\"declared\")\n\
         }\n",
    );
    for a in app.actions.iter().filter(|a| a.native) {
        let Some(t) = tool(manifest, &format!("{}/{}", app.app_id, a.name)) else {
            continue;
        };
        let input = &t["inputSchema"];
        let (args, _) = example(input);
        let id = ident(&a.name);
        let _ = writeln!(
            s,
            "\n#[test]\nfn {id}_schema() {{\n    let input = &tool(\"{name}\")[\"inputSchema\"];\n    validate(input, &json!({args})).unwrap();",
            name = a.name,
            args = js(&args)
        );
        if input["required"].as_array().is_some_and(|r| !r.is_empty()) {
            let _ = writeln!(s, "    assert!(validate(input, &json!({{}})).is_err());");
        }
        let mut extra = args.as_object().cloned().unwrap_or_else(Map::new);
        extra.insert("unexpected".into(), Value::from(1));
        let _ = writeln!(
            s,
            "    assert!(validate(input, &json!({})).is_err());\n}}",
            js(&Value::Object(extra))
        );
        let ignore = if a.destructive || a.open_world || a.confirm {
            "#[ignore = \"acts on real data or the network: run it against test data\"]\n"
        } else {
            ""
        };
        let _ = writeln!(
            s,
            "\n#[test]\n{ignore}fn {id}_invoke() {{\n    let result = keel::invoke(\"{name}\", json!({args})).expect(\"registered\").wait();\n    if let Err(e) = &result {{\n        assert_ne!(e.code, keel::ErrorCode::InvalidArguments, \"{{e}}\");\n    }}\n    // TODO: check the result (or the effect of the action).\n}}",
            name = a.name,
            args = js(&args)
        );
    }
    Artefact {
        name: "keel_actions_tests.rs".into(),
        contents: s,
    }
}

/// Resolves `@TESTS@/<file>` placeholders for a tests directory.
pub fn place(stub: &Artefact, tests_dir: &Path) -> Artefact {
    let mut contents = String::new();
    let mut rest = stub.contents.as_str();
    while let Some(start) = rest.find("@TESTS@/") {
        contents.push_str(&rest[..start]);
        let after = &rest[start + 8..];
        let end = after.find('"').unwrap_or(after.len());
        contents.push_str(
            &relative(Path::new(&after[..end]), tests_dir)
                .display()
                .to_string(),
        );
        rest = &after[end..];
    }
    contents.push_str(rest);
    Artefact {
        name: stub.name.clone(),
        contents,
    }
}
