// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: MIT
//
// QML plugin for the `Keel` module:
//   Keel.Ambience - ambience values (Rust, CXX-Qt: keel/silica/plugin/src)
//   Keel.Shell    - keel-shell client (shellclient.h)
//   Keel.LinkParser - links in plain text (Rust, CXX-Qt; Silica's
//                   LinkedLabel uses it as Sailfish.Silica.private's LinkParser)
// Registration is imperative because the Ambience QObject is generated by
// CXX-Qt outside this CMake target, so qmltyperegistrar cannot see it.

#include "shellclient.h"
#include "keel_silica_native/src/ambience.cxxqt.h"
#include "keel_silica_native/src/linkparser.cxxqt.h"

#include <QQmlEngine>
#include <QQmlExtensionPlugin>

extern void qml_register_types_Keel();

namespace {

QObject *createAmbience(QQmlEngine *, QJSEngine *)
{
    auto *ambience = new keel::Ambience;
    keel::ShellClient *shell = keel::ShellClient::instance();
    auto apply = [ambience, shell]() {
        ambience->applyForwarded(keel::ShellClient::ambienceLines(shell->ambience()));
    };
    QObject::connect(shell, &keel::ShellClient::ambienceChanged, ambience, apply);
    if (!shell->ambience().isEmpty())
        apply();
    return ambience;
}

QObject *createShell(QQmlEngine *, QJSEngine *)
{
    keel::ShellClient *shell = keel::ShellClient::instance();
    QQmlEngine::setObjectOwnership(shell, QQmlEngine::CppOwnership);
    return shell;
}

} // namespace

class KeelPlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

public:
    explicit KeelPlugin(QObject *parent = nullptr)
        : QQmlExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Keel;
        Q_UNUSED(registration)
    }

    // Called after the engine has claimed the "Keel" namespace for this
    // plugin; registering earlier (in the constructor) is rejected.
    void registerTypes(const char *uri) override
    {
        qmlRegisterSingletonType<keel::Ambience>(uri, 1, 0, "Ambience", createAmbience);
        qmlRegisterType<keel::LinkParser>(uri, 1, 0, "LinkParser");
        qmlRegisterSingletonType<keel::ShellClient>(uri, 1, 0, "Shell", createShell);
    }
};

#include "keelplugin.moc"
