// SPDX-FileCopyrightText: 2026 Patrick Quinn
// SPDX-License-Identifier: Apache-2.0
//
// New file, added by Shipwright in 2026 (not part of upstream xmatic).

//! How phone numbers saved without a country code are read: the dialling
//! plan of the user's home country.
//!
//! The country comes from the SIM where there is one: the C++ side asks
//! oFono for the SIM's mobile country code (`org.ofono.SimManager`
//! `MobileCountryCode`, else the network's, `org.ofono.NetworkRegistration`).
//! Without a SIM (or oFono) it falls back to the locale's country, which is
//! only a guess: a phone set to British English in Germany reads "0170..."
//! as a UK number. Without either, numbers without a country code are
//! matched on their last digits only (`contacts.rs`).
//!
//! The table (`core/data/mcc-dialling.tsv`) maps every MCC in the ITU list to
//! its region, calling code and prefixes. It is generated by
//! `tools/mcc-dialling.py` from AOSP's `MccTable.java` and libphonenumber's
//! metadata, both Apache-2.0; the file names the exact revisions.
//!
//! What it does not know: area codes, number lengths and regional quirks
//! such as Argentina's mobile "15" or Mexico's former "1". A plan only says
//! which calling code goes in front and which national prefix comes off.

use std::collections::BTreeMap;
use std::sync::OnceLock;

const TABLE: &str = include_str!("../data/mcc-dialling.tsv");

/// One country's dialling plan.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Plan {
    /// ISO 3166 alpha-2, upper case ("DE").
    pub region: String,
    /// The E.164 calling code, digits only ("49").
    pub calling_code: String,
    /// The trunk prefix dialled before a national number ("0"; "1" in the
    /// NANP; "8" in Russia). Empty where there is none (Italy).
    pub national_prefix: String,
    /// The prefix dialled before a calling code ("00", "011"). Empty where
    /// the metadata gives only a pattern.
    pub international_prefix: String,
    /// Where the plan came from: "sim" or "locale".
    pub source: &'static str,
}

impl Plan {
    /// `digits` (everything but '+' stripped) in international form, or
    /// `None` where the plan cannot tell.
    pub fn international(&self, digits: &str) -> Option<String> {
        // Dialled from abroad. "00" as well, which most of the world uses and
        // which no national number starts with.
        for prefix in [self.international_prefix.as_str(), "00"] {
            if prefix.is_empty() {
                continue;
            }
            if let Some(rest) = digits.strip_prefix(prefix) {
                if rest.len() >= 5 {
                    return Some(format!("+{rest}"));
                }
            }
        }
        if self.national_prefix.is_empty() {
            // No trunk prefix: the number is dialled the same way inside and
            // outside the country, leading zero included (Italy, San Marino).
            return Some(format!("+{}{digits}", self.calling_code));
        }
        if let Some(rest) = digits.strip_prefix(self.national_prefix.as_str()) {
            return Some(format!("+{}{rest}", self.calling_code));
        }
        // The NANP is written without its trunk prefix more often than with:
        // ten digits are a whole national number there.
        if self.calling_code == "1" && digits.len() == 10 {
            return Some(format!("+1{digits}"));
        }
        // Anywhere else a number without its trunk prefix is local (no area
        // code), and the country code alone would make a wrong number.
        None
    }
}

struct Row {
    region: &'static str,
    calling_code: &'static str,
    national_prefix: &'static str,
    international_prefix: &'static str,
}

fn none_if_dash(field: &'static str) -> &'static str {
    if field == "-" {
        ""
    } else {
        field
    }
}

fn rows() -> &'static BTreeMap<&'static str, Row> {
    static ROWS: OnceLock<BTreeMap<&'static str, Row>> = OnceLock::new();
    ROWS.get_or_init(|| {
        TABLE
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
            .filter_map(|line| {
                let mut fields = line.split('\t');
                let mcc = fields.next()?;
                let row = Row {
                    region: fields.next()?,
                    calling_code: fields.next()?,
                    national_prefix: none_if_dash(fields.next()?),
                    international_prefix: none_if_dash(fields.next()?),
                };
                Some((mcc, row))
            })
            .collect()
    })
}

fn plan(row: &Row, source: &'static str) -> Plan {
    Plan {
        region: row.region.to_owned(),
        calling_code: row.calling_code.to_owned(),
        national_prefix: row.national_prefix.to_owned(),
        international_prefix: row.international_prefix.to_owned(),
        source,
    }
}

/// The plan for a mobile country code ("262").
pub fn for_mcc(mcc: &str) -> Option<Plan> {
    rows().get(mcc.trim()).map(|row| plan(row, "sim"))
}

/// The plan for an ISO 3166 region ("DE", "de"). Several MCCs can share a
/// region (the US has seven); they share its plan too.
pub fn for_region(region: &str) -> Option<Plan> {
    let region = region.trim().to_ascii_uppercase();
    rows()
        .values()
        .find(|row| row.region == region)
        .map(|row| plan(row, "locale"))
}

/// The SIM's plan where it is known, else the locale's.
pub fn resolve(mcc: &str, region: &str) -> Option<Plan> {
    for_mcc(mcc).or_else(|| for_region(region))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_complete_and_well_formed() {
        let rows = rows();
        // The ITU list has well over two hundred codes; a truncated file
        // would silently fall back to the locale everywhere.
        assert!(rows.len() > 230, "only {} rows", rows.len());
        for (mcc, row) in rows {
            assert_eq!(mcc.len(), 3, "{mcc}");
            assert!(mcc.chars().all(|c| c.is_ascii_digit()), "{mcc}");
            assert_eq!(row.region.len(), 2, "{mcc}");
            assert!(row.region.chars().all(|c| c.is_ascii_uppercase()), "{mcc}");
            assert!(!row.calling_code.is_empty(), "{mcc}");
            assert!(
                row.calling_code.chars().all(|c| c.is_ascii_digit()),
                "{mcc}"
            );
            assert!(
                row.national_prefix.chars().all(|c| c.is_ascii_digit()),
                "{mcc}"
            );
            assert!(
                row.international_prefix.chars().all(|c| c.is_ascii_digit()),
                "{mcc}"
            );
        }
    }

    #[test]
    fn mobile_country_codes_map_to_calling_codes() {
        for (mcc, region, code) in [
            ("262", "DE", "49"),
            ("232", "AT", "43"),
            ("244", "FI", "358"),
            ("234", "GB", "44"),
            ("235", "GB", "44"),
            ("310", "US", "1"),
            ("316", "US", "1"),
            ("302", "CA", "1"),
            ("334", "MX", "52"),
            ("250", "RU", "7"),
            ("401", "KZ", "7"),
            ("404", "IN", "91"),
            ("405", "IN", "91"),
            ("440", "JP", "81"),
            ("460", "CN", "86"),
            ("505", "AU", "61"),
            ("530", "NZ", "64"),
            ("655", "ZA", "27"),
            ("724", "BR", "55"),
            ("222", "IT", "39"),
        ] {
            let plan = for_mcc(mcc).unwrap_or_else(|| panic!("{mcc} missing"));
            assert_eq!(plan.region, region, "{mcc}");
            assert_eq!(plan.calling_code, code, "{mcc}");
            assert_eq!(plan.source, "sim");
        }
        assert_eq!(for_mcc("999"), None);
        assert_eq!(for_mcc(""), None);
    }

    #[test]
    fn the_sim_wins_over_the_locale() {
        // A German SIM in a phone set to British English.
        let plan = resolve("262", "GB").expect("plan");
        assert_eq!((plan.calling_code.as_str(), plan.source), ("49", "sim"));
        // No SIM: the locale's country.
        let plan = resolve("", "gb").expect("plan");
        assert_eq!((plan.calling_code.as_str(), plan.source), ("44", "locale"));
        // An MCC the table does not know is no SIM.
        let plan = resolve("000", "FI").expect("plan");
        assert_eq!(plan.calling_code, "358");
        assert_eq!(resolve("", ""), None);
        assert_eq!(resolve("", "ZZ"), None);
    }

    #[test]
    fn national_numbers_become_international() {
        let de = for_region("DE").expect("DE");
        assert_eq!(
            de.international("01701234567").as_deref(),
            Some("+491701234567")
        );
        assert_eq!(
            de.international("00441234567890").as_deref(),
            Some("+441234567890")
        );
        // No area code: not something a country code can fix.
        assert_eq!(de.international("1234567"), None);

        let us = for_region("US").expect("US");
        assert_eq!(
            us.international("2025550123").as_deref(),
            Some("+12025550123")
        );
        assert_eq!(
            us.international("12025550123").as_deref(),
            Some("+12025550123")
        );
        assert_eq!(
            us.international("011491701234567").as_deref(),
            Some("+491701234567")
        );
        assert_eq!(us.international("5550123"), None);

        // Italy keeps the leading zero.
        let it = for_region("IT").expect("IT");
        assert_eq!(
            it.international("0612345678").as_deref(),
            Some("+390612345678")
        );
        assert_eq!(
            it.international("3123456789").as_deref(),
            Some("+393123456789")
        );

        // Russia's trunk prefix is 8, its international prefix 810.
        let ru = for_region("RU").expect("RU");
        assert_eq!(
            ru.international("89161234567").as_deref(),
            Some("+79161234567")
        );
        assert_eq!(
            ru.international("810491701234567").as_deref(),
            Some("+491701234567")
        );
    }
}
